src/Redit_app/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('bil/', include('billing.urls',namespace="celery_progress"))
]

src/billing/urls.py
from .views import progress_view

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.urls import path,include

app_name="billing"

urlpatterns = [
    url('res', progress_view, name="task_status")
] 

##if settings.DEBUG:
##    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/billing/models.py
from django.db import models







class BillingItem(models.Model):
    number1   = models.IntegerField(default="5")
    number2   = models.IntegerField(default="6")
    total      = models.IntegerField(default="7")
    item_name  = models.CharField(max_length=120, null=True, blank=True)
    timestamp  = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
    	return "{total}".format(total=self.total)

    def __str__(self):
        return "{total}".format(total=self.total) 	

src/billing/views.py
from .tasks import my_task
from django.shortcuts import render,redirect


def progress_view(request):
    result = my_task.delay(10)
    return render(request, 'display_progress.html', context={'task_id': result.task_id})

src/billing/templates/display_progress.html
<div class='progress-wrapper'>
  <div id='progress-bar' class='progress-bar' style="background-color: #68a9ef; width: 0%;">&nbsp;</div>
</div>
<div id="progress-bar-message">Waiting for progress to start...</div>





<script type="text/javascript">
var progressUrl = "{% url 'celery_progress:task_status' task_id %}";

$(function () {
  CeleryProgressBar.initProgressBar(progressUrl)
});
</script>